name: go
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1'
      - uses: codecov/codecov-action@v1
      - run: apt-get install libasound2-dev -y
      - run: go get golang.org/x/tools/cmd/goimports
      - run: go test ./...
      - run: go build ./...
